UPDATE_USER_SPATIAL_INFORMATION_OPCODE = 0x00
SELECT_OBJECT_OPCODE = 0x01

UPDATE_OBJECT_SPATIAL_INFORMATION_OPCODE = 0x10
SEND_USER_ID_OPCODE = 0x11
SELECT_OBJECT_RESPONSE_OPCODE = 0x12

SEND_IMPLEMENTATION_SPECIFIC_MESSAGE = 0xFF 

COMMAND_LENGTHS = {
  UPDATE_USER_SPATIAL_INFORMATION_OPCODE : 24,
  SELECT_OBJECT_OPCODE : 4,
        
  UPDATE_OBJECT_SPATIAL_INFORMATION_OPCODE : 68,
  SEND_USER_ID_OPCODE : 4,
  SELECT_OBJECT_RESPONSE_OPCODE : 1,
}       

